plugins {
    id 'net.neoforged.moddev' version '2.0.143'
}

version = project.mod_version
group = project.maven_group
base { archivesName = project.archives_base_name }

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
            systemProperty 'neoforge.warnings.logofile.hide', 'true'
        }
        server { server() }
    }

    mods {
        "${project.archives_base_name}" {
            sourceSet(sourceSets.main)
        }
    }
}

repositories {
    maven { url = "https://maven.neoforged.net/releases/" }
    maven { url = "https://api.modrinth.com/maven" }
}

dependencies {
    implementation "maven.modrinth:midnightlib:${project.midnightlib_version}"
}

processResources {
    inputs.property "version", project.mod_version
    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.mod_version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
}
