org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
minecraft_version=26.1.2
loader_version=0.18.4
mod_version=3.0.0-26.1.2
maven_group=net.wolren
archives_base_name=reach_display
fabric_version=0.150.0+26.1.2
midnightlib_version=1.9.3+26.1-fabric
mixinextras_version=0.5.4

# Quilt build (-PuseQuilt=true)
quilt_loader_version=0.30.0-beta.8
quilted_fabric_api_version=11.0.0-alpha.3+0.102.0-1.21
