modLoader="javafml"
loaderVersion="[4,)"
license="ARR"
issueTrackerURL="https://github.com/Wolren/ReachDisplay/issues"

[[mods]]
modId="reach_display"
version="${version}"
displayName="Reach Display"
iconFile="assets/reach_display/icon.png"
authors="Wolren"
description='''A configurable visual representation of your reach and hit distances'''

[[dependencies.reach_display]]
    modId="neoforge"
    type="required"
    versionRange="[21.11,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.reach_display]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.11,1.21.12)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.reach_display]]
    modId="midnightlib"
    type="required"
    versionRange="[1.9,)"
    ordering="NONE"
    side="CLIENT"

[[mixins]]
config="reach_display.mixins.json"
